export const clients = [
  { name: 'Walmart', src: '/clients/walmart.png' },
  { name: 'Exxon', src: '/clients/exxon.png' },
  { name: 'PNC', src: '/clients/PNC.png' },
  { name: 'Memorial Hermann', src: '/clients/memorial-hermann.png' },
  { name: 'City of Houston', src: '/clients/city-of-houston.png' },
  { name: 'Harris County', src: '/clients/harris-county.png' },
  { name: 'JLL', src: '/clients/JLL.png' },
  { name: 'Mitsubishi', src: '/clients/mitsubishi.png' },
  { name: 'METRO', src: '/clients/metro.png' },
  { name: 'Comerica', src: '/clients/comerica.png' },
  { name: 'EXP', src: '/clients/EXP.png' },
  { name: 'BGE', src: '/clients/BGE.png' },
  { name: 'RelaDyne', src: '/clients/reladyne.png' },
  { name: 'Emerus', src: '/clients/emerus.png' },
  { name: 'AccessHealth', src: '/clients/access-health.png' },
  { name: 'Spirit', src: '/clients/spirit.png' },
  { name: 'Mac Haik', src: '/clients/machaik.png' },
  { name: 'Cedar', src: '/clients/cedar.png' },
] as const;
