export const projectCategories = [
  'Aviation',
  'Energy',
  'Healthcare',
  'Industrial',
  'Public Sector',
  'Commercial',
  'Litigation',
] as const;

export type ProjectCategory = (typeof projectCategories)[number];

export type Project = {
  slug: string;
  title: string;
  location: string;
  category: ProjectCategory;
  image: string;
  imageAlt: string;
  bullets: string[];
};

export const projects: Project[] = [
  {
    slug: 'international-airport-terminal',
    title: 'International Airport Terminal',
    location: 'Houston, Texas',
    category: 'Aviation',
    image: '/projects/international-airport-terminal.jpg',
    imageAlt: 'International Airport Terminal — Houston, Texas',
    bullets: [
      'Performed detailed hazardous materials assessment following a fire event.',
      'Evaluated for asbestos, PCBs, dioxins, heavy metals, chemicals, lead, and mold.',
      'Cross-training and dual licensing allowed for use of a small, efficient team to reduce cost and mobilizations.',
      'Responded to rapid requests for mold clearance investigations and confirmation sampling.',
      'Guided Client through the RFP process, initial assessment and throughout remediation to project completion.',
      'Performed all work discretely and during Site occupancy to allow continuous client operations.',
    ],
  },
  {
    slug: 'reladyne-northern-california',
    title: 'Bulk Fuel/Lubricant Terminal Facility Portfolio RelaDyne, Inc.',
    location: 'Northern California',
    category: 'Energy',
    image: '/projects/reladyne-northern-california.jpg',
    imageAlt: 'Bulk Fuel/Lubricant Terminal Facility Portfolio RelaDyne, Inc. — Northern California',
    bullets: [
      'Involved a multi-site business/asset acquisition portfolio that were positioned across the Sacramento Valley.',
      'Conducted ASTM E1527-21 compliant Phase I Environmental Site Assessments, which included Non-Scope Considerations (asbestos, lead, and mold) to evaluate for potential employee health and safety concerns.',
      'Evaluated for potential environmental risks specific to representations and warranties involving each property transaction.',
      'Conducted an out-of-scope sub-slab vapor investigation based on documented evidence of a previous vapor intrusion condition.',
    ],
  },
  {
    slug: 'george-bush-intercontinental-airport',
    title: 'George Bush Intercontinental Airport',
    location: 'Houston, Texas',
    category: 'Aviation',
    image: '/projects/george-bush-intercontinental-airport.jpg',
    imageAlt: 'George Bush Intercontinental Airport — Houston, Texas',
    bullets: [
      'Comprehensive hazardous materials assessment & inspections.',
      'Discretely sampled and evaluated 90% of the airport during occupancy to allow airport operations to continue.',
      'Identified, delineated and provided oversight during the abatement and remediation of various hazards including regulated mold, asbestos-containing materials, lead-based paints and PCB-containing dusts.',
      'Universal waste audit management guidance and oversight.',
      'Monitored air results daily.',
    ],
  },
  {
    slug: 'galdisa-usa',
    title: 'Galdisa USA',
    location: 'Conroe, Texas',
    category: 'Industrial',
    image: '/projects/galdisa-usa.jpg',
    imageAlt: 'Galdisa USA — Conroe, Texas',
    bullets: [
      'Conducted an ASTM E1527-21 compliant Phase I Environmental Site Assessment at a peanut product manufacturing facility.',
      'Compliance recommendations made to the client regarding proper disposal of used cooking oil drums and grease trap.',
      'Review of historical resources revealed that the subject property and the surrounding properties had been developed within the past 15-years.',
    ],
  },
  {
    slug: 'reladyne-missouri',
    title: 'Bulk Fuel/Lubricant Terminal Facility Portfolio RelaDyne, Inc.',
    location: 'Missouri',
    category: 'Energy',
    image: '/projects/reladyne-missouri.jpg',
    imageAlt: 'Bulk Fuel/Lubricant Terminal Facility Portfolio RelaDyne, Inc. — Missouri',
    bullets: [
      'Involved a multi-site business/asset acquisition portfolio positioned across various Missouri locations.',
      'Conducted ASTM E1527-21 compliant Phase I Environmental Site Assessments, which included Non-Scope Considerations (asbestos, lead, and mold) to evaluate for potential employee health and safety concerns.',
      'Evaluated for potential environmental risks specific to representations and warranties involving each property transaction.',
    ],
  },
  {
    slug: 'mitsubishi-ferrocote-air-testing',
    title: 'Mitsubishi Ferrocote Air Testing',
    location: 'Houston, Texas',
    category: 'Industrial',
    image: '/projects/mitsubishi-ferrocote-air-testing.jpg',
    imageAlt: 'Mitsubishi Ferrocote Air Testing — Houston, Texas',
    bullets: [
      'Involved the monitoring and sampling of air within a facility utilizing a chemical (Ferrocote) as a protective application to equipment with potential harm to employees.',
      'Monitoring involved utilizing area and personnel air samples to determine the concentration of Ferrocote within the vicinity of employees over a typical 12-hour shift.',
      'Additionally, direct-read data of standard air parameters (relative humidity, temperature, carbon monoxide, carbon dioxide, and air particulates) were also collected to supplement the monitoring of Ferrocote.',
    ],
  },
  {
    slug: 'mitsubishi-heavy-industry-compressor-corporation',
    title: 'Mitsubishi Heavy Industry Compressor Corporation',
    location: 'Houston, Texas',
    category: 'Industrial',
    image: '/projects/mitsubishi-heavy-industry-compressor-corporation.jpg',
    imageAlt: 'Mitsubishi Heavy Industry Compressor Corporation — Houston, Texas',
    bullets: [
      'Performed baseline & follow-on testing for VOCs, refrigerant gas, vibration levels and decibels.',
      'Able to evaluate impacts to indoor air quality via the collection of real time particulate sampling and indoor air parameter data.',
      'Utilized Client-provided documentation to prepare a useable sampling plan and evaluate compliance with OSHA statute.',
      'Established federal, state and local action levels, which was then able to adequately enhance the Site’s Hearing Conservation Program.',
    ],
  },
  {
    slug: 'hurricane-harvey-flood-recovery-kingwood-critical-care-center',
    title: 'Hurricane Harvey Flood Recovery Kingwood Critical Care Center',
    location: 'Kingwood, Texas',
    category: 'Healthcare',
    image: '/projects/hurricane-harvey-flood-recovery-kingwood-critical-care-center.jpg',
    imageAlt: 'Hurricane Harvey Flood Recovery Kingwood Critical Care Center — Kingwood, Texas',
    bullets: [
      'Sole consultant for MHHS over an 8-month facility recovery period.',
      'Expedited hygiene disaster recovery assessment for asbestos, mold, and bacteriological impact.',
      'Established environmental compliance strategies and implemented detailed remediation protocols.',
      'Diligent implementation of remediation protocols, daily project oversight, inspection of remediation progress.',
    ],
  },
  {
    slug: 'discovery-green-park-conservancy',
    title: 'Discovery Green Park / Conservancy',
    location: 'Houston, Texas',
    category: 'Public Sector',
    image: '/projects/discovery-green-park-conservancy.jpg',
    imageAlt: 'Discovery Green Park / Conservancy — Houston, Texas',
    bullets: [
      'Phase I & II ESA for 7 City Blocks',
      'Groundwater Plume Delineation & groundwater monitoring-“Ghost” PST Removal',
      'Confirmatory Testing & Reporting',
      'APAR/RAP/RACR Preparation',
      'Soil/Fill Material Characterization',
      'VCP/LPST Case Closure',
      'Construction Site Monitoring',
    ],
  },
  {
    slug: 'emerus-hospitals',
    title: 'Emerus Hospitals',
    location: 'Las Vegas, Nevada',
    category: 'Healthcare',
    image: '/projects/emerus-hospitals.jpg',
    imageAlt: 'Emerus Hospitals — Las Vegas, Nevada',
    bullets: [
      'Phase I & II Site Assessment',
      'Extensive asbestos abatement, waste management.',
      'Multiple lifts removed and soil excavated to remediate the site.',
      'Designed, installed and tested a vapor barrier system for the new hospital structure.',
      'Location was converted from an automotive facility to an emergency hospital.',
    ],
  },
  {
    slug: 'industrial-food-distribution-facility',
    title: 'Industrial Food Distribution Facility',
    location: 'Arcadia, Florida',
    category: 'Industrial',
    image: '/projects/industrial-food-distribution-facility.jpg',
    imageAlt: 'Industrial Food Distribution Facility — Arcadia, Florida',
    bullets: [
      'All-inclusive service through “sick building” investigation, remediation, and initiation of a new facility cleaning protocol tailored to the unique climate and regulatory conditions.',
      'Managed remediation oversight.',
      'Project was completed while allowing the distribution center to operate at near full capacity with quadrant-specific remediation and various shift work.',
    ],
  },
  {
    slug: 'national-oilwell-varco-harvey-pipe-inspection-plant-storage',
    title: 'National Oilwell Varco Harvey Pipe Inspection Plant / Storage Yard Decommissioning',
    location: 'Harvey, Louisiana',
    category: 'Energy',
    image: '/projects/national-oilwell-varco-harvey-pipe-inspection-plant-storage.jpg',
    imageAlt: 'National Oilwell Varco Harvey Pipe Inspection Plant / Storage Yard Decommissioning — Harvey, Louisiana',
    bullets: [
      'Remediation of NORM-impacted soils.',
      'Due Diligence research into historical facility operations.',
      'Surveys for asbestos.',
      'Coordinated excavation, waste profiling, transportation, disposal, and agency approvals.',
      'Remediation was implemented with the regulated excavation/disposal of radioactive soils from 17 areas.',
    ],
  },
  {
    slug: '100-acre-class-a-project',
    title: '100-acre, Class A+ Project',
    location: 'Miami, Florida',
    category: 'Industrial',
    image: '/projects/100-acre-class-a-project.jpg',
    imageAlt: '100-acre, Class A+ Project — Miami, Florida',
    bullets: [
      'Identified areas of impact to the environment (including petroleum and solvent impacted soil), tested associated areas of concern via the installation of monitor wells/soil borings and removed (by excavation) impacted media prior to re-development.',
      'Designed and oversaw the installation of the required vapor intrusion mitigation and passive venting system and worked closely with the state regulatory agency to meet project objectives.',
    ],
  },
  {
    slug: 'bbva-compass-bank',
    title: 'BBVA Compass Bank',
    location: 'Houston, Texas',
    category: 'Commercial',
    image: '/projects/bbva-compass-bank.jpg',
    imageAlt: 'BBVA Compass Bank — Houston, Texas',
    bullets: [
      'Due Diligence assessments and Industrial Hygiene surveys.',
      'Asbestos abatement prior to building demolition.',
      'Excavation/removal of former USTs and hydraulic lifts',
      'Monitored groundwater and exhaustive peer review of extensive neighboring cases.',
      'Soil vapor studies.',
      'Designed, installation, oversite and testing of a vapor intrusion mitigation system.',
    ],
  },
  {
    slug: 'former-jet-hangar-service-facility',
    title: 'Former Jet Hangar & Service Facility',
    location: 'Houston, Texas',
    category: 'Aviation',
    image: '/projects/former-jet-hangar-service-facility.jpg',
    imageAlt: 'Former Jet Hangar & Service Facility — Houston, Texas',
    bullets: [
      'Performed assessment and abatement monitoring services for a three-story commercial building constructed with two hangar bays.',
      'Conducted a full evaluation for asbestos, lead, metals, hydrocarbon release, as well as PCBs in light fixtures and building finishes.',
      'Identified and delineated hidden wall cavity materials to accurately scope abatement and demolition costs.',
      'Able to mobilize and continue abatement immediately following Hurricane Beryl to avoid project delays.',
      'Provided oversight and air monitoring during the excavation and removal of buried asbestos-containing materials.',
      'Rapidly prepared asbestos specifications for the proper management of contaminated soils.',
      'Employed an emergency response team to sample subgrade equipment contents and soils to rule out additional Site hazards.',
      'Refuted findings provided within a competitor’s report by utilizing qualified labs that saved Client days of abatement services.',
    ],
  },
  {
    slug: 'greenstar-recycling',
    title: 'Greenstar Recycling',
    location: '6+ States',
    category: 'Industrial',
    image: '/projects/greenstar-recycling.jpg',
    imageAlt: 'Greenstar Recycling — 6+ States',
    bullets: [
      'Portfolio included a recycling facility with several plants nationwide to handle comprehensive environmental due diligence efforts for a pending divestiture including asbestos and other built environment hazards.',
      'Completed various Phase I Environmental Site Assessments, Preliminary Compliance Reviews, as well as State/Federal file reviews.',
      'Completed permitting, plans and training for Greenstar operations with regard to various federal and state regulations inclusive of SARA Title III, the Oil Pollution Prevention Act, the Clean Water Act, and the Resource Conservation and Recovery Act.',
    ],
  },
  {
    slug: 'david-wayne-hooks-memorial-airport',
    title: 'David Wayne Hooks Memorial Airport',
    location: 'Houston, Texas',
    category: 'Aviation',
    image: '/projects/david-wayne-hooks-memorial-airport.jpg',
    imageAlt: 'David Wayne Hooks Memorial Airport — Houston, Texas',
    bullets: [
      'Completed a Phase I ESA, limited asbestos survey, and preliminary compliance and non-scope consideration.',
      'Extensive historical/regulatory research revealed that the property was improved as a private airport since the 1960s and operated by various airplane maintenance and operation entities involved in waste generation activities with an extensive history of non-compliance, underground petroleum storage with documented releases.',
      'Observed current non-permitted land applied waste activities lead to the discovery of a reported experimental landfill area proving the possible presence of extensive buried waste materials within the Site limits.',
    ],
  },
  {
    slug: 'giddings-independent-school-district',
    title: 'Giddings Independent School District',
    location: 'Giddings, Texas',
    category: 'Public Sector',
    image: '/projects/giddings-independent-school-district.jpg',
    imageAlt: 'Giddings Independent School District — Giddings, Texas',
    bullets: [
      'Performed a comprehensive pre-demolition asbestos survey, concurrent with a comprehensive haz-mat inspection of a former elementary school.',
      'Collected over 250 asbestos samples and identified polychlorinated biphenyls (PCBs), mercury, metals, hydrocarbons, Freon, chemicals, and areas containing lead-based paint.',
      'Utilized priority S.T.O.P. (Strategic Testing and Operations Program) process to expedite the abatement bidding, specification preparation, and planning process to save project funds.',
    ],
  },
  {
    slug: 'west-gray-taft-paving-and-draining-project',
    title: 'West Gray & Taft Paving and Draining Project',
    location: 'Houston, Texas',
    category: 'Public Sector',
    image: '/projects/west-gray-taft-paving-and-draining-project.jpg',
    imageAlt: 'West Gray & Taft Paving and Draining Project — Houston, Texas',
    bullets: [
      'Characterized and reconciled RECs associated with numerous historical/current commercial/industrial properties, per ASTM/AAI via completion of a Limited Phase II ESA.',
      'Coordinated site access with both the City of Houston and individual property owners, coordinated and implemented traffic control measures, completed field work and reporting requirements within Client-specified timeframe.',
    ],
  },
  {
    slug: 'proposed-hospital-site',
    title: 'Proposed Hospital Site',
    location: 'Liberty, Texas',
    category: 'Healthcare',
    image: '/projects/proposed-hospital-site.jpg',
    imageAlt: 'Proposed Hospital Site — Liberty, Texas',
    bullets: [
      'Lead extensive Site and records review to adequately determine the safety of establishing a sensitive facility on a 34-acre property.',
      'Investigated the USDA Scope Specific “Special Topics” considerations which assessed for historical significance, endangered species, wetlands, asbestos, lead-based paint, methamphetamine laboratories, radon, and formaldehyde insulation to name a few.',
      'Identification of a natural storm event that led to buried waste at the Site and an understanding of prior and current agricultural use that would assist in generating opinion on future action.',
      'Protected the Client from a likely vapor encroachment condition, the material threat of release from on-site and off-site operations, and prepared Client for response actions warranted when developing a Site that provides a habitat for endangered species, is improved with wetlands and subject to flooding.',
    ],
  },
  {
    slug: 'turner-construction-company',
    title: 'Turner Construction Company',
    location: 'Bay City, Texas',
    category: 'Industrial',
    image: '/projects/turner-construction-company.jpg',
    imageAlt: 'Turner Construction Company — Bay City, Texas',
    bullets: [
      'Managed and oversaw mold assessment, remediation, and Clearance for the 12 functional areas.',
      'Completed remediation within 90 days of the event without loss or permanent damage to vital equipment; the majority of affected sheetrock was saved from demolition, cleaned, and treated effectively with an antimicrobial coating (for future antimicrobial benefits).',
      'No reoccurrence of mold found up to date.',
      'This project would prove to be the largest single mold remediation effort under TMARR notification for a single facility, with millions of square feet of mold-impacted surfaces involved.',
    ],
  },
  {
    slug: 'old-yacht-club',
    title: 'Old Yacht Club',
    location: 'Port Arthur, Texas',
    category: 'Litigation',
    image: '/projects/old-yacht-club.jpg',
    imageAlt: 'Old Yacht Club — Port Arthur, Texas',
    bullets: [
      'Extensive history of marine servicing activity dating back to the 1970s for the Site and adjoining land, adjacent oil and gas activity, as well as prior Municipal Landfill use for at least a decade preceding current federal regulations and standards.',
      'During the detailed regulatory database and State file review, identification of the presence of an adjoining Superfund facility.',
      'Provided the client with supporting evidence of contract non-compliance, which was utilized as supporting material regarding on-going litigation involving the previous tenant.',
    ],
  },
  {
    slug: 'fort-bend-isd',
    title: 'Fort Bend ISD',
    location: 'Fort Bend, Texas',
    category: 'Public Sector',
    image: '/projects/fort-bend-isd.jpg',
    imageAlt: 'Fort Bend ISD — Fort Bend, Texas',
    bullets: [
      'Extensive history of marine servicing activity dating back to the 1970s for the Site and adjoining land, adjacent oil and gas activity, as well as prior Municipal Landfill use for at least a decade preceding current federal regulations and standards.',
      'During the detailed regulatory database and State file review, identification of the presence of an adjoining Superfund facility.',
      'Provided the client with supporting evidence of contract non-compliance, which was utilized as supporting material regarding on-going litigation involving the previous tenant.',
    ],
  },
  {
    slug: 'pipeline-litigation-investigation',
    title: 'Pipeline Litigation Investigation',
    location: 'Bryan, Texas',
    category: 'Litigation',
    image: '/projects/pipeline-litigation-investigation.jpg',
    imageAlt: 'Pipeline Litigation Investigation — Bryan, Texas',
    bullets: [
      'Investigated and confirmed a reported release of petroleum products from a gas gathering line located adjacent to a residential property.',
      'Planned and managed multiple sample events to identify, quantify, and delineate the contamination and release from the pipeline.',
      'Geotechnical surveys over multiple properties, in-situ soil and soil gas investigation, indoor air quality assessments, and groundwater sampling in the process of designing a remedial option for soil gas.',
      'After confirmation of release, constant communication with the Texas Railroad Commission expedited allowed for successful installation engineering controls on the property.',
    ],
  },
  {
    slug: 'fifth-ward-community-redevelopment-corporation-city-of-houston',
    title: 'Fifth Ward Community Redevelopment Corporation & City of Houston',
    location: 'Houston, Texas',
    category: 'Public Sector',
    image: '/projects/fifth-ward-community-redevelopment-corporation-city-of-houston.jpg',
    imageAlt: 'Fifth Ward Community Redevelopment Corporation & City of Houston — Houston, Texas',
    bullets: [
      'Identified the presence of extensive regulated mold; friable and non-friable asbestos-containing materials; and varying concentrations of lead in coatings across painted surfaces.',
      'Facilitated the revitalization and renovation (with limited demolition) of a former historic hospital complex comprised of five, distinct, multi-story buildings with multiple episodes of original construction and renovation.',
    ],
  },
  {
    slug: 'mantle-oil-gas-grand-gulf-energy',
    title: 'Mantle Oil & Gas, Grand Gulf Energy',
    location: 'Louisiana',
    category: 'Energy',
    image: '/projects/mantle-oil-gas-grand-gulf-energy.jpg',
    imageAlt: 'Mantle Oil & Gas, Grand Gulf Energy — Louisiana',
    bullets: [
      'Responded with containment, reclamation, and expedited site characterization for released reserves via comprehensive environmental due diligence.',
      'Innovative environmental engineering solutions were implemented to control crude release and manage contaminated media.',
      'Provided litigation support and expert witness services to assist with estimated losses and drive fact-based defense.',
    ],
  },
];

